# Generated by Django 5.1.6 on 2025-04-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConctactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.CharField(blank=True, max_length=225, null=True)),
                ('number', models.CharField(blank=True, max_length=225, null=True)),
                ('interest', models.CharField(blank=True, max_length=225, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
