# Generated by Django 5.1.6 on 2025-04-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('course', models.CharField(max_length=225)),
                ('education', models.CharField(max_length=225)),
                ('experience', models.CharField(max_length=225)),
                ('batch', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
