# Generated by Django 5.2 on 2025-05-21 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='heare_about_us',
            field=models.CharField(default=datetime.datetime(2025, 5, 21, 12, 46, 24, 871478, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(default=datetime.datetime(2025, 5, 21, 12, 46, 28, 969373, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
